# -*- mode: shell-script; coding: utf-8; fill-column: 78; -*-

#
# Common Bash customizations that should always be enabled for login shells.
#
# Author: Mike LaSpina
#

if [[ -r "$HOME/.bashrc" ]]; then
  source "$HOME/.bashrc"
fi


